"""removed Google rating column, replaced with in-app rating

Revision ID: 4b64eae51a50
Revises: 5d554351cada
Create Date: 2025-09-24 15:19:04.690723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b64eae51a50'
down_revision = '5d554351cada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.drop_column('google_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_rating', sa.NUMERIC(precision=2, scale=1), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
